### ISSUE TITLE
proposal to change module names

### ISSUE THREAD

**Issue by frasertweedale** [purebred-mua/purebred-mailcap#6]
I propose a different module naming scheme for this library.

RFCs can be updated or superseded by later RFCs.  The idea of naming a data library
after an RFC number is therefore flawed.  I went through the same thing with *purebred-email*,
and switched from `Data.RFC5322` to `Data.IMF`.

Therefore for *purebred-mailcap* I'd suggest `Data.Mailcap` as the main module, with supporting
or supplementary modules `Data.Mailcap.Whatever`.

**Comment by romanofski** [comment]
Ah right.. thanks for that lesson learned. I'll make that a rename and basically move what is currently in `RFC1524` into `Data.Mailcap` and the folder `RFC1524` will be renamed to `Mailcap`. 

So basically before:

```
src/Data/
├── Mailcap.hs
├── RFC1524
│   ├── Internal.hs
│   └── ViewCommand.hs
└── RFC1524.hs
```

and after:
```
src/Data/
├── Mailcap.hs
├── Mailcap
│   ├── Internal.hs
│   └── ViewCommand.hs
```

**Comment by frasertweedale** [comment]
That looks good to me.  Ideally everything a "normal" use case requires should be exported through `Data.Mailcap`.
