### ISSUE TITLE
Let purebred-mailcap build the ProcessConfig

### ISSUE THREAD

**Issue by romanofski** [purebred-mua/purebred-mailcap#8]
The mailcap provides templates on how shell commands are executed. @frasertweedale suggested one function, e..g:

```Haskell
prepareProcess :: MailcapEntry -> Message s B.Bytestring -> ProcessConfig i o e
```

provided by the library returning a process config. That config can then be executed by purebred.

**Comment by romanofski** [comment]
See #9 as the alternate approach

**Comment by frasertweedale** [comment]
I think I want to reject this approach already.  Making / cleaning up temporary files involves a lot of policy decisions that i think it's better to leave to the application.

This does not entirely preclude building a `ProcessConfig`, though.  I just means that *purebred-mailcap* should not be responsible for creating temporary files, etc.

**Comment by frasertweedale** [comment]
Closing in favour of #9.
